### ISSUE TITLE
Crash on 32-bit ARM

### ISSUE THREAD

**Issue by leshik** [bodymindarts/risq#14]
I tried to build `risq` on RPi and the daemon crashes on start. I suppose it might be related to some `int64` alignment issues (which is a usual thing on 32-bit ARM).

`RUST_LOG=debug RUST_BACKTRACE=1 ./target/debug/risq daemon`

```
[2019-10-23T11:30:55Z INFO  actix_server::builder] Starting 4 workers
[2019-10-23T11:30:55Z INFO  actix_server::builder] Starting server on 127.0.0.1:7477
[2019-10-23T11:30:55Z INFO  risq::p2p::bootstrap] Bootstrapping from seed: NodeAddress { host_name: "3f3cu2yw7u457ztq.onion", port: 8000 }
[2019-10-23T11:30:55Z INFO  risq::domain::price_feed] Updating price feed via http://gztmprecgqjq64zh.onion/getAllMarketPrices
[2019-10-23T11:30:55Z DEBUG tokio_reactor::background] starting background reactor
[2019-10-23T11:30:58Z INFO  risq::p2p::server] Server started @ NodeAddress { host_name: "pm64lsy5piqndvqc.onion", port: 9999 }
[2019-10-23T11:30:58Z DEBUG tokio_reactor] adding I/O source: 0
[2019-10-23T11:30:58Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 0
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 4194305
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 8388610
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 12582915
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 1
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 2
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 3
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 0
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:03Z DEBUG hyper::proto::h1::io] flushed 130 bytes
[2019-10-23T11:31:03Z DEBUG risq::p2p::bootstrap] Sending PreliminaryGetDataRequest to seed.
[2019-10-23T11:31:03Z DEBUG tokio_reactor] adding I/O source: 4194305
[2019-10-23T11:31:03Z DEBUG tokio_reactor::registration] scheduling Read for: 1
[2019-10-23T11:31:03Z DEBUG risq::p2p::connection] Sending message PreliminaryGetDataRequest(PreliminaryGetDataRequest { nonce: 546780086, excluded_keys: [], supported_capabilities: [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12] })
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] read 3486 bytes
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] parsed 4 headers
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::conn] incoming body is chunked encoding
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::decode] incoming chunked header: 0x2000 (8192 bytes)
[2019-10-23T11:31:04Z DEBUG reqwest::async_impl::response] Response: '200 OK' for http://gztmprecgqjq64zh.onion/getAllMarketPrices
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] read 3486 bytes
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] read 4482 bytes
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::decode] incoming chunked header: 0x2000 (8192 bytes)
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] read 4930 bytes
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::io] read 6148 bytes
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::decode] incoming chunked header: 0x1743 (5955 bytes)
[2019-10-23T11:31:04Z DEBUG hyper::proto::h1::conn] incoming body completed
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2019-10-23T11:31:04Z DEBUG hyper::client::pool] pooling idle connection for "http://gztmprecgqjq64zh.onion"
thread 'main' panicked at 'overflow when adding duration to instant', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1166
  11: core::option::Option<T>::expect
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/option.rs:345
  12: <std::time::Instant as core::ops::arith::Add<core::time::Duration>>::add
             at src/libstd/time.rs:312
  13: <risq::domain::price_feed::PriceData as core::convert::From<risq::domain::price_feed::PriceDataRaw>>::from
             at src/domain/price_feed.rs:143
  14: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
  15: core::result::Result<T,E>::map
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:512
  16: risq::domain::price_feed::_IMPL_DESERIALIZE_FOR_PriceData::<impl serde::de::Deserialize for risq::domain::price_feed::PriceData>::deserialize
             at src/domain/price_feed.rs:106
  17: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/mod.rs:786
  18: <serde_json::de::SeqAccess<R> as serde::de::SeqAccess>::next_element_seed
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:1739
  19: serde::de::SeqAccess::next_element
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/mod.rs:1708
  20: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/impls.rs:866
  21: <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_seq
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:1529
  22: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/impls.rs:877
  23: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/mod.rs:786
  24: <serde_json::de::MapAccess<R> as serde::de::MapAccess>::next_value_seed
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:1801
  25: serde::de::MapAccess::next_value
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/mod.rs:1847
  26: <risq::domain::price_feed::_IMPL_DESERIALIZE_FOR_GetAllMarketPricesResponse::<impl serde::de::Deserialize for risq::domain::price_feed::GetAllMarketPricesResponse>::deserialize::__Visitor as serde::de::Visitor>::visit_map
             at src/domain/price_feed.rs:115
  27: <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:1628
  28: risq::domain::price_feed::_IMPL_DESERIALIZE_FOR_GetAllMarketPricesResponse::<impl serde::de::Deserialize for risq::domain::price_feed::GetAllMarketPricesResponse>::deserialize
             at src/domain/price_feed.rs:115
  29: serde_json::de::from_trait
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:2184
  30: serde_json::de::from_slice
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/de.rs:2302
  31: <reqwest::async_impl::response::Json<T> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.9.22/src/async_impl/response.rs:284
  32: futures::future::chain::Chain<A,B,C>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:32
  33: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:32
  34: <actix::fut::FutureWrap<F,A> as actix::fut::ActorFuture>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/fut/mod.rs:418
  35: <actix::fut::map::Map<A,F> as actix::fut::ActorFuture>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/fut/map.rs:40
  36: <actix::fut::map_err::MapErr<A,F> as actix::fut::ActorFuture>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/fut/map_err.rs:40
  37: <alloc::boxed::Box<F> as actix::fut::ActorFuture>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/fut/mod.rs:342
  38: <actix::contextimpl::ContextFut<A,C> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/contextimpl.rs:373
  39: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  40: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  41: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  42: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  43: futures::task_impl::std::set
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  44: futures::task_impl::Spawn<T>::enter
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  45: futures::task_impl::Spawn<T>::poll_fn_notify
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  46: futures::task_impl::Spawn<T>::poll_future_notify
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  47: tokio_current_thread::scheduler::Scheduled<U>::tick
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:351
  48: tokio_current_thread::scheduler::Scheduler<U>::tick::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:330
  49: tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788
  50: tokio_current_thread::CurrentRunner::set_spawn
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:825
  51: tokio_current_thread::Borrow<U>::enter::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:788
  52: std::thread::local::LocalKey<T>::try_with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
  53: std::thread::local::LocalKey<T>::with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
  54: tokio_current_thread::Borrow<U>::enter
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:786
  55: tokio_current_thread::scheduler::Scheduler<U>::tick
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/scheduler.rs:330
  56: tokio_current_thread::Entered<P>::tick
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:612
  57: tokio_current_thread::Entered<P>::block_on
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.6/src/lib.rs:502
  58: actix_rt::runtime::Runtime::block_on::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:128
  59: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:168
  60: tokio_executor::global::with_default::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
  61: std::thread::local::LocalKey<T>::try_with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
  62: std::thread::local::LocalKey<T>::with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
  63: tokio_executor::global::with_default
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
  64: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:166
  65: tokio_timer::timer::handle::with_default::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
  66: std::thread::local::LocalKey<T>::try_with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
  67: std::thread::local::LocalKey<T>::with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
  68: tokio_timer::timer::handle::with_default
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
  69: actix_rt::runtime::Runtime::enter::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:159
  70: tokio_timer::clock::clock::with_default::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
  71: std::thread::local::LocalKey<T>::try_with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
  72: std::thread::local::LocalKey<T>::with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
  73: tokio_timer::clock::clock::with_default
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
  74: actix_rt::runtime::Runtime::enter::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:158
  75: tokio_reactor::with_default::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  76: std::thread::local::LocalKey<T>::try_with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
  77: std::thread::local::LocalKey<T>::with
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
  78: tokio_reactor::with_default
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  79: actix_rt::runtime::Runtime::enter
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:157
  80: actix_rt::runtime::Runtime::block_on
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/runtime.rs:126
  81: actix_rt::builder::SystemRunner::run
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.5/src/builder.rs:209
  82: risq::daemon::run
             at src/daemon.rs:63
  83: risq::cli::daemon
             at src/cli.rs:150
  84: risq::cli::run
             at src/cli.rs:76
  85: risq::main
             at src/main.rs:4
  86: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  87: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  88: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  89: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  90: std::panicking::try
             at src/libstd/panicking.rs:275
  91: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  92: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  93: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  94: main
  95: __libc_start_main
Panic in Arbiter thread, shutting down system.
[2019-10-23T11:31:05Z DEBUG tokio_reactor] dropping I/O source: 0
[2019-10-23T11:31:05Z DEBUG tokio_reactor] dropping I/O source: 1
[2019-10-23T11:31:05Z DEBUG tokio_reactor] dropping I/O source: 2
[2019-10-23T11:31:05Z DEBUG tokio_reactor] dropping I/O source: 3
[2019-10-23T11:31:05Z DEBUG tokio_reactor] dropping I/O source: 0
```

**Comment by bodymindarts** [comment]
Thanks for the backtrace. I think the issue is coming from [here](https://github.com/bodymindarts/risq/blob/master/src/domain/price_feed.rs#L143).

I just checked and it looks like the price nodes are actually returning the unix time in milliseconds NOT seconds:
```
$ curl -s http://174.138.104.137:8080/getAllMarketPrices | jq .data | head
[
  {
    "currencyCode": "AED",
    "price": 29320.04,
    "timestampSec": 1571831482544,
    "provider": "BTCA_G"
  },
```
I'll fix that and we'll see if it changes something. Might also be an issue with the underlying representation 64bit vs 32 bit.
How did you compile it for raspi? Using [cross](https://github.com/rust-embedded/cross) to cross compile or directly on the box?

**Comment by bodymindarts** [comment]
Whoops... it auto closed because I wrote 'Maybe fix'

**Comment by leshik** [comment]
`cross` didn’t work for me (it complained about `openssl` something, probably due to missing cross `libssl-dev` in docker image, so I compiled directly on Pi.

**Comment by bodymindarts** [comment]
Yeah I'm not happy about the external openssl dependency. Just wanted to get the crypto stuff working for now to move forward. Hopefully we can find a better library that can be statically compiled later.

**Comment by bodymindarts** [comment]
What compile target and which [tier](https://forge.rust-lang.org/release/platform-support.html) is it?

**Comment by leshik** [comment]
I used `arm-unknown-linux-gnueabihf`, thus Tier 2. Though not required for my RPi (`rustup` auto-detected it as `armv7-unknown-linux-gnueabihf`), I preferred the former to make sure it works on other RPis such as Zero (which is ARMv6 HF.)

**Comment by leshik** [comment]
#15 fixed it, awesome! Thanks!
